version: "3.9"
services:
  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./app/frontend
      dockerfile: Dockerfile
    ports:
      - "7860:7860"
