version: "3.8"
services:
  frontend:
    build:
      context: ./app/frontend
    ports:
      - "3000:3000"
    networks:
      - app-network  
    depends_on:
      - backend  

  backend:
    build:
      context: ./app/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - app-network  

networks:
  app-network:
    driver: bridge  

