version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "7860:7860"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
